# Generated by Django 3.2.21 on 2023-10-12 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20231008_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='Enter discount as percentage(e.g., 10 for 10 %)', null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Enter a fixed discount amount.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Promtions',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.promotion'),
        ),
    ]
