# Generated by Django 3.2.21 on 2023-10-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231012_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name_plural': 'Promotions'},
        ),
    ]
